---
  - name: Update system
    become: true
    apt:
      update-cache: true
  - name: Install Required Dependencies
    become: true
    apt:
      name: '{{ item }}'
      state: present
    with_items:
      - python3
      - python-setuptools
      - python3-dev
      - build-essential
      - python3-pip
      - python3-mysqldb
      - python3-pymysql
