---
  - name: Install Flask and Dependencies
    become: true
    pip:
      name: '{{ item }}'
      state: present
      executable: pip3.10
    with_items:
      - Werkzeug==2.2.2
      - flask==2.1.3
      - flask-mysql
  - name: Copy source code
    get_url:
      url: https://raw.githubusercontent.com/mmumshad/simple-webapp/master/app.py
      dest: /home/ubuntu/app.py
  - name: Start Web Server
    shell: FLASK_APP=/home/ubuntu/app.py nohup flask run --host=0.0.0.0 --port 5000 &
    environment:
      MYSQL_DATABASE_HOST: '{{ db_server_public_ip }}'
